[package]
name = "kvs"
version = "0.1.0"
edition = "2021"
authors = ["Kould <2435992353@qq.com>"]
description = "A key-value store"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = { version = "0.1.5", features = ["derive"] }
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
bincode = "1.3.3"
rmp-serde = "1.1.0"
tokio = { version="1", features = ["full"] }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
memmap2 = "0.5.4"
tokio-util = { version="0.7.3", features = ["codec"] }
tokio-stream = "0.1.9"
bytes = "1.2.1"
clap = { version = "3.1.18", features = ["derive"] }

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"
tokio-test = "*"
