[package]
name = "kvs"
version = "0.1.0"
edition = "2021"
authors = ["Kould <2435992353@qq.com>"]
description = "A key-value store"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.15", features = ["derive"] }
failure = { version = "0.1.5", features = ["derive"] }
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
axum = "0.4"
tokio = { version="1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"
